version: "2.0"
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh-user:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5wDmVb4jWiTsds9lNhsfNUQGfraNDmYqmgD+OmPrYLPxTPe+0z+XgzFsI6cIQG+fXRfqCp/VkHZH40AT8GvC1cIPKl+vbJN296rQ+Q+saoUY1+FjLYlXIFGEWcb/EtMLtsVTQDT3eWZyv1ZpxmLi3TQxbXEME/Te6q8q1LLfkkqfsgNcy8UpLKTwKGElvnFjhtIC0GLgqT65L2aSdr/o6MDSxQMRwFqpr+Hxc2841q93hlciNnw+lObRgJ47rKUmV6AkMf53+TyGZCZ4wiautJXYoowE+3wWMTgBT/2Dqdt/z+irsswRZfL97fvIuVUp06CNUcdceoADL6lrc91reYnfl41axUrsGcP3lVUQJD0cGqo/sd59yNp3OwouGHHDfd3BEged9cRSG4C/EKuPEiYyj0ZzKQzfDLAv96aIADCr3JL0TozLUGyJt0tM1UNSlGG4BDsc+7rRM5Ll7wRJ/pZgZPolScyitASBmNzQbuZDwctozXals5IqUfhb5aywLN3y9L3287++U01C6CQBh/5Dls0CMH2nzD9jF4Rf339bn2d8FUbSrlXkEs1GWgtCr7VzOfLkpdTB/D2ZSiyDO+UL5EelvusMdbKyCptRppWMrldddQkhcESXP3rVoz2YhgT4DhUqenp0LKUcSLWnuZf4r38LBHavuz3YSoVnNkQ== azuread\peterkuvshinov@Intern-Laptop

      - username=swantouser
    expose:
        - port: 22
        - port: 30002
        - port: 30003
        - port: 30004
        - port: 30005
        - port: 30006
        - port: 30007
deployment:
  vm:
    lagrange:
      count: 1
